### ISSUE TITLE
Both player's king has sente mark

### ISSUE THREAD

**Issue by gbtami** [orangain/shogi-piece-images#1]
Seems Shogi_gyokusho(svg).svg was used for both king generation.
It would be nice to have osho piece also (not just gyokusho).

**Comment by orangain** [comment]
@gbtami Thank you for the suggestion! Now both osho (`0OU.svg`, `1OU.svg`) and gyokusho (`0GY.svg`, `1GY.svg`) are available in `dist` directory.

**Comment by gbtami** [comment]
Thx a lot!
