### ISSUE TITLE
Put pieces into square

### ISSUE THREAD

**Issue by gbtami** [orangain/shogi-piece-images#2]
Is it possible to modify the scale step script to make all svg drawings into a square (width=height) instead of rectangle, and center them horizontally? I want to use your shogi piece images with https://github.com/ornicar/chessground (my clone can handle some >= 8x8 board geometry), but it's scaling logic assumes that svg pieces has same width and height. I can do this cosmetic work myself by hand using inkscape, but it would be more elegant if an alternate version of 2_scale.sh/2_scale.js can do this also.

**Comment by orangain** [comment]
@gbtami  I think piece images should be rectangle as it is because each cell of shogi board is basically a rectangle not a square. 

However, as you say, it is possible to make these images into square by modifying the script. You need to make two files:

`scripts/9_square.js`

```js
const fs = require('fs');

const input = fs.readFileSync('/dev/stdin', 'utf8');

let offset;
let output = input.replace(/width="([\d.]+)"\s*height="([\d.]+)"/, (match, p1, p2) => {
    const width = parseFloat(p1);
    const height = parseFloat(p2);
    offset = (height - width) / 2
    return `width="${height}" height="${height}"`;
});

output = output.replace('<g ', `<g transform="translate(${offset} 0)"><g `);
output = output.replace('</g>', '</g></g>');

console.log(output);
```

`scripts/9_scale.sh`

```sh
#!/bin/bash

FROM_DIR=$1
TO_DIR=$2

mkdir -p $TO_DIR

find $FROM_DIR -name '*.svg' -exec sh -c "node scripts/9_square.js < {} > \$(echo {} | sed s@$FROM_DIR@$TO_DIR@)" \;
```

You can generate square images by the following command. After running the command, you will see square images in `square` directory.

```
$ bash ./scripts/9_square.sh dist square
```

**Comment by gbtami** [comment]
You are absolutely right and I'm a bit ashamed missing this fact. I will look into chessground code to see if I can use squared pieces with a squared board. Anyhow, really appreciated for your help!
Arigato gozaimashita.

**Comment by gbtami** [comment]
My latest question :) Shouldn't be pawn images a little bit smaller than all other pieces?

**Comment by orangain** [comment]
I didn't think of it until you said 💡  As you say, it would be more natural if pawn images are little bit smaller than other pieces. However, I don't have strong motivation to make these images more natural for now. If other people also want natural images, I'll think about it at that time.

**Comment by gbtami** [comment]
No problem. I managed to create rectangle shaped board in my shogi .css and now I can use your awesome pieces as is in my chessground based project.
![](http://i.imgur.com/RyZHgyf.png)
Finally I used your 9_square.js (with little modification) on playok xiangqi .svg pieces which are really needed to be in squares.
Thx all of your help again!

**Comment by orangain** [comment]
I'm grad to hear that! 😄 Thank you for letting me know.
